Repository startsheep/Administrator-Griya-Jambudipa, pull requests merged in 2022-08, with the labels that each got.

#7 example membuat routes, route dibuat masing-masing file
  routes/api.php
  routes/api/auth.php
  routes/example/company_profile.php
  routes/example/employee.php
  routes/example/position.php
  routes/url/auth.php
  routes/web.php
Labels: documentation

#9 Feature/agj 45 view pegawai
  public/assets/css/bootstrap.min.css
  public/assets/css/custom.css
  public/assets/fontawesome-free-6.1.2-web/modules-datatables.js
  public/assets/images/avatar/avatar-1.png
  public/assets/images/avatar/avatar-2.png
  public/assets/images/avatar/avatar-3.png
  public/assets/images/avatar/avatar-4.png
  public/assets/images/avatar/avatar-5.png
  public/assets/js/modules-datatables.js
  public/assets/third-party/datatables/Readme.md
  public/assets/third-party/datatables/license.txt
  public/assets/third-party/datatables/media/css/jquery.dataTables.css
  public/assets/third-party/datatables/media/css/jquery.dataTables.min.css
  public/assets/third-party/datatables/media/images/Sorting icons.psd
  public/assets/third-party/datatables/media/images/favicon.ico
  public/assets/third-party/datatables/media/images/sort_asc.png
  public/assets/third-party/datatables/media/images/sort_asc_disabled.png
  public/assets/third-party/datatables/media/images/sort_both.png
  public/assets/third-party/datatables/media/images/sort_desc.png
  public/assets/third-party/datatables/media/images/sort_desc_disabled.png
  public/assets/third-party/datatables/media/js/jquery.dataTables.js
  public/assets/third-party/datatables/media/js/jquery.dataTables.min.js
  public/assets/third-party/datatables/package.json
  resources/views/layouts/main-layout.blade.php
  resources/views/layouts/sidebar.blade.php
  resources/views/pages/dashboard.blade.php
  resources/views/pages/pegawai/v-pegawai.blade.php
  routes/web.php
Labels: enhancement

#26 Feature/AGJ-53-FE-crud-jabatan
  package-lock.json
  package.json
  resources/css/app.css
  resources/css/stisla/custom.css
  resources/js/app.js
  resources/js/components/CircleLoader.vue
  resources/js/components/Pagination.vue
  resources/js/pages/employees/Employees.vue
  resources/js/router/routes.js
  resources/js/store/services/utils.js
Labels: enhancement

#32 Feature/AGJ-62-FE-crud-pegawai
  app/Http/Repositories/EmployeeRepository.php
  app/Http/Requests/Employee/UpdateEmployeeRequest.php
  resources/css/stisla/custom.css
  resources/js/pages/employees/CreateEditEmployee.vue
  resources/js/pages/employees/Division.vue
  resources/js/pages/employees/Employees.vue
  resources/js/router/modules/employees.js
  resources/js/router/routes.js
  resources/js/store/index.js
  resources/js/store/modules/employee.js
  resources/js/store/services/action.js
Labels: enhancement

#46 👌Fix Kavling
  resources/js/pages/kavling/CreateEdi.vue
  resources/js/pages/kavling/Kavling.vue
Labels: bug

#49 Feature/agj 82 preview image before upload
  app/Http/Repositories/EmployeeRepository.php
  resources/js/pages/customers/CreateEditCustomer.vue
  resources/js/pages/employees/CreateEditEmployee.vue
Labels: enhancement

#55 Feature/agj 85 fe detail customer
  resources/js/pages/customers/Customers.vue
  resources/js/pages/customers/DetailCustomer.vue
  resources/js/store/services/action.js
Labels: enhancement

#56 Feature/agj 101 detail pengguna
  resources/css/stisla/bootstrap.min.css
  resources/js/pages/users/DetailUser.vue
  resources/js/pages/users/Users.vue
  resources/js/store/modules/user/logic.js
Labels: enhancement
